export const convexApi = {
  settings: {
    get: "settings:get",
    setOpenRouterKey: "settings:setOpenRouterKey",
    clearOpenRouterKey: "settings:clearOpenRouterKey",
    setGeminiKey: "settings:setGeminiKey",
    clearGeminiKey: "settings:clearGeminiKey",
  },
  deepDives: {
    list: "deepDives:list",
    get: "deepDives:get",
    createDeepDive: "deepDives:createDeepDive",
    createThread: "deepDives:createThread",
    addUploads: "deepDives:addUploads",
    removeUpload: "deepDives:removeUpload",
    deleteDeepDive: "deepDives:deleteDeepDive",
    appendUserMessage: "deepDives:appendUserMessage",
    createInvite: "deepDives:createInvite",
    listInvites: "deepDives:listInvites",
    listMyInvites: "deepDives:listMyInvites",
    declineInvite: "deepDives:declineInvite",
    getInviteInfo: "deepDives:getInviteInfo",
    acceptInvite: "deepDives:acceptInvite",
    leaveDeepDive: "deepDives:leaveDeepDive",
    listMembers: "deepDives:listMembers",
    updateMemberRole: "deepDives:updateMemberRole",
    removeMember: "deepDives:removeMember",
    listHumanChatMessages: "deepDives:listHumanChatMessages",
    sendHumanChatMessage: "deepDives:sendHumanChatMessage",
  },
  ai: {
    sendThreadMessage: "ai:sendThreadMessage",
    runVote: "ai:runVote",
    runDebate: "ai:runDebate",
  },
} as const;
