export const convexApi = {
  settings: {
    get: "settings:get",
    setOpenRouterKey: "settings:setOpenRouterKey",
    clearOpenRouterKey: "settings:clearOpenRouterKey",
    setGeminiKey: "settings:setGeminiKey",
    clearGeminiKey: "settings:clearGeminiKey",
    addApiKey: "settings:addApiKey",
    deleteApiKey: "settings:deleteApiKey",
  },
  deepDives: {
    list: "deepDives:list",
    get: "deepDives:get",
    getThread: "deepDives:getThread",
    migrateLegacyThreadMessages: "deepDives:migrateLegacyThreadMessages",
    createDeepDive: "deepDives:createDeepDive",
    updateDeepDiveTitle: "deepDives:updateDeepDiveTitle",
    createThread: "deepDives:createThread",
    updateThreadTitle: "deepDives:updateThreadTitle",
    deleteThread: "deepDives:deleteThread",
    addUploads: "deepDives:addUploads",
    removeUpload: "deepDives:removeUpload",
    deleteDeepDive: "deepDives:deleteDeepDive",
    appendUserMessage: "deepDives:appendUserMessage",
    createInvite: "deepDives:createInvite",
    listInvites: "deepDives:listInvites",
    listMyInvites: "deepDives:listMyInvites",
    declineInvite: "deepDives:declineInvite",
    getInviteInfo: "deepDives:getInviteInfo",
    acceptInvite: "deepDives:acceptInvite",
    leaveDeepDive: "deepDives:leaveDeepDive",
    listMembers: "deepDives:listMembers",
    heartbeat: "deepDives:heartbeat",
    listOnlineMembers: "deepDives:listOnlineMembers",
    updateMemberRole: "deepDives:updateMemberRole",
    removeMember: "deepDives:removeMember",
    listHumanChatMessages: "deepDives:listHumanChatMessages",
    sendHumanChatMessage: "deepDives:sendHumanChatMessage",
  },
  ai: {
    sendThreadMessage: "ai:sendThreadMessage",
    runVote: "ai:runVote",
    runDebate: "ai:runDebate",
  },
} as const;
